# Created by:	Eric Turgeon ericturgeon@ghostbsd.org
# Date created:	November 11 2013


PORTNAME=	networkmgr
PORTVERSION=	1.3
PORTREVISION=	0
CATEGORIES=	net-mgmt
MASTER_SITES=	https://github.com/DesktopBSD/${PORTNAME}/archive/

MAINTAINER=	ericturgeon@ghostbsd.org
COMMENT=	GTK network manager.

LICENSE=	BSD

USE_GITHUB=	yes
GH_ACCOUNT=	DesktopBSD

USES = python:2
USE_PYTHON=	distutils
USE_GNOME=	pygtk2

.include <bsd.port.mk>
